//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EService.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLiteContext : DbContext
    {
        public SQLiteContext()
            : base("name=SQLiteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dept> Dept { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<ParameterForModel> ParameterForModel { get; set; }
        public virtual DbSet<ParameterValue> ParameterValue { get; set; }
        public virtual DbSet<Repairer> Repairer { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceCategory> ServiceCategory { get; set; }
        public virtual DbSet<ServiceDone> ServiceDone { get; set; }
        public virtual DbSet<ServiceForModel> ServiceForModel { get; set; }
        public virtual DbSet<ServiceLog> ServiceLog { get; set; }
        public virtual DbSet<Spare> Spare { get; set; }
        public virtual DbSet<SpareForModel> SpareForModel { get; set; }
        public virtual DbSet<SpareUsed> SpareUsed { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TypeModel> TypeModel { get; set; }
    }
}
