//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EService.Data.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class ParameterValue : INotifyPropertyChanged, IIdentifier
    {
        long rowid;
        long rowidParameterForModel;
        long rowidServiceLog;
        string value;
        ParameterForModel parameterForModel;
        ServiceLog serviceLog;

        public long Rowid { get { return rowid; } set { rowid = value; OnPropertyChanged("Rowid"); } }
        public long RowidParameterForModel { get { return rowidParameterForModel; } set { rowidParameterForModel = value; OnPropertyChanged("RowidParameterForModel"); } }
        public long RowidServiceLog { get { return rowidServiceLog; } set { rowidServiceLog = value; OnPropertyChanged("RowidServiceLog"); } }
        public string Value { get { return value; } set { this.value = value; OnPropertyChanged("Value"); } }

        public virtual ParameterForModel ParameterForModel { get { return parameterForModel; } set { parameterForModel = value; OnPropertyChanged("ParameterForModel"); } }
        public virtual ServiceLog ServiceLog { get { return serviceLog; } set { serviceLog = value; OnPropertyChanged("ServiceLog"); } }

        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged([CallerMemberName] string property = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
        }
    }
}
