//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EService.Data.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class ServiceDone : INotifyPropertyChanged
    {
        long rowid;
        long rowidServiceForModel;
        long rowidServiceLog;
        ServiceLog serviceLog;
        ServiceForModel serviceForModel;

        public long Rowid { get { return rowid; } set { rowid = value; OnPropertyChanged("Rowid"); } }
        public long RowidServiceForModel { get { return rowidServiceForModel; } set { rowidServiceForModel = value; OnPropertyChanged("RowidServiceForModel"); } }
        public long RowidServiceLog { get { return rowidServiceLog; } set { rowidServiceLog = value; OnPropertyChanged("RowidServiceLog"); } }

        public virtual ServiceLog ServiceLog { get { return serviceLog; } set { serviceLog = value; OnPropertyChanged("ServiceLog"); } }
        public virtual ServiceForModel ServiceForModel { get { return serviceForModel; } set { serviceForModel = value; OnPropertyChanged("ServiceForModel"); } }

        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged([CallerMemberName] string property = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(property));
        }
    }
}
